models:
  - "MOIRAI"
  # - "PatchTST"
  # - "DLinear"
  # - "TimesNet"
  # - "TFT"
  # - "NBEATS"
  # - "NHITS"

  # - "TSMixer"
  # - "iTransformer"

configs:
  - "./model/moirai.yaml"
  # - "./model/patchtst.json"
  # - "./model/patchtst.json"
  # - "./model/patchtst.json"
  # - "./model/patchtst.json"
  # - "./model/patchtst.json"
  # - "./model/patchtst.json"

  # - "./model/tsmixer.json"
  # - "./model/tsmixer.json"

data_path: "./data/ETTh1.csv"
time_col: "date"
batch_size: 128

max_steps: 5000
max_epochs: 100

logger: "wandb"

horizon: 96
lookback: 96
