models:
  # - "MOIRAI": "./model/moirai.yaml"

  - "PatchTST"
  - "DLinear"
  - "TimesNet"
  - "TFT"
  - "NBEATS"
  - "NHITS"

  - "TSMixer"
  - "iTransformer"

data_path: "./data/ETTh1.csv"
is_local: true
time_col: "date"
batch_size: 128

max_steps: 5000
max_epochs: 100

logger: "wandb"

horizon: 96
lookback: 96
