_target_: uni2ts.model.moirai.MoiraiFinetune.load_from_checkpoint
beta1: 0.9
beta2: 0.98
checkpoint_path:
  _target_: huggingface_hub.hf_hub_download
  filename: model.ckpt
  repo_id: Salesforce/moirai-1.0-R-small
loss_func:
  _target_: uni2ts.loss.packed.PackedNLLLoss
lr: 1e-3
max_dim: 128
max_mask_ratio: 0.5
min_mask_ratio: 0.15
min_patches: 2
module_kwargs:
  _target_: builtins.dict
  attn_dropout_p: 0.0
  d_model: 384
  distr_output:
    _target_: uni2ts.distribution.MixtureOutput
    components:
    - _target_: uni2ts.distribution.StudentTOutput
    - _target_: uni2ts.distribution.NormalFixedScaleOutput
    - _target_: uni2ts.distribution.NegativeBinomialOutput
    - _target_: uni2ts.distribution.LogNormalOutput
  dropout_p: 0.0
  max_seq_len: 512
  num_layers: 6
  patch_sizes: ${as_tuple:[8, 16, 32, 64, 128]}
  scaling: true
num_training_steps: ${mul:${trainer.max_epochs},${train_dataloader.num_batches_per_epoch}}
num_warmup_steps: 0
val_metric:
- _target_: uni2ts.loss.packed.PackedMSELoss
- _target_: uni2ts.loss.packed.PackedNRMSELoss
  normalize: absolute_target_squared
weight_decay: 1e-1
